### ISSUE TITLE
红米k40, 锁屏状态无法通过密码解锁

### ISSUE THREAD

**Issue by scott-wong** [fangyk-rel/DingDing-SayNo#13]
点击执行后直接1秒退出，没提示什么信息

**Comment by fykrel** [comment]
可以看看脚本日志

**Comment by scott-wong** [comment]
自己直接改代码解决了，没仔细研究，主要改了手势的起止位置
`gesture(3000, [w / 2, 2000], [w / 2, 1000]);`
