### ISSUE TITLE
转成auto js

### ISSUE THREAD

**Issue by hjjcq2017** [fangyk-rel/DingDing-SayNo#5]
楼主，咨询一下我将代码转成autojs脚本了，如何解决节假日数据以及自动打卡的问题，谢谢了

**Comment by fykrel** [comment]
> 楼主，咨询一下我将代码转成autojs脚本了，如何解决节假日数据以及自动打卡的问题，谢谢了

节假日数据来源于网络上的免费接口，可以配置jumpRules字段控制
jumpRules = ”rule_0“，表示不跳过节假日和周末
jumpRules = ”rule_1“，表示跳过节假日
jumpRules = ”rule_2“，表示跳过周末
jumpRules = ”rule_3“，表示跳过节假日和周末

自动打卡的话你可以去研究Tasker这个App，设置好权限后，可以配置定时启动Atuo.js

**Comment by hjjcq2017** [comment]
谢谢老兄了我去测试一下


fangyk-rel <notifications@github.com> 于 2021年3月5日周五 上午9:21写道：
